# Generated by Django 5.1.5 on 2025-01-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='drones', to='drones.medication'),
        ),
    ]
