# Generated by Django 5.1.5 on 2025-01-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_alter_drone_serial_number_batterylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
