# Generated by Django 5.1.5 on 2025-01-21 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_alter_drone_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='code',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='image',
        ),
        migrations.AlterField(
            model_name='drone',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='DroneMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_medications', to='drones.drone')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.medication')),
            ],
        ),
    ]
