# Generated by Django 5.1.5 on 2025-01-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_remove_medication_code_remove_medication_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='code',
            field=models.CharField(default='default_code', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.ImageField(default='default_code', upload_to='medications/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=models.CharField(choices=[('Available', 'Available'), ('Loading', 'Loading'), ('Low Battery', 'Low Battery'), ('Delivering', 'Delivering')], default='Available', max_length=100),
        ),
        migrations.DeleteModel(
            name='DroneMedication',
        ),
    ]
