# Generated by Django 5.1.5 on 2025-01-21 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0007_alter_drone_model_alter_drone_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Code must contain only uppercase letters, numbers, and underscores.', regex='^[A-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medication_images/'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, dashes, and underscores.', regex='^[a-zA-Z0-9-_]+$')]),
        ),
    ]
