# Generated by Django 5.1.5 on 2025-01-21 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0008_alter_medication_code_alter_medication_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterylog',
            name='battery_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batterylog',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_logs', to='drones.drone'),
        ),
        migrations.AlterField(
            model_name='batterylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
